// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkWdiOhmSSEmYdOD9epiGIkx7FS-IJo5g',
    appId: '1:503116412521:web:09fa4e4a2ae9c9afe494f8',
    messagingSenderId: '503116412521',
    projectId: 'chatapp-70e51',
    authDomain: 'chatapp-70e51.firebaseapp.com',
    storageBucket: 'chatapp-70e51.appspot.com',
    measurementId: 'G-BYH3XBR9VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN8Ghml-b4fC7ppVDoLh5zK4qzv5hzyeg',
    appId: '1:503116412521:android:9a0e8feae694c679e494f8',
    messagingSenderId: '503116412521',
    projectId: 'chatapp-70e51',
    storageBucket: 'chatapp-70e51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkCX9mnYmgVqBYR9cp-hoAMgZAkZ-ZptE',
    appId: '1:503116412521:ios:030b9a477925d369e494f8',
    messagingSenderId: '503116412521',
    projectId: 'chatapp-70e51',
    storageBucket: 'chatapp-70e51.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkCX9mnYmgVqBYR9cp-hoAMgZAkZ-ZptE',
    appId: '1:503116412521:ios:030b9a477925d369e494f8',
    messagingSenderId: '503116412521',
    projectId: 'chatapp-70e51',
    storageBucket: 'chatapp-70e51.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkWdiOhmSSEmYdOD9epiGIkx7FS-IJo5g',
    appId: '1:503116412521:web:6f72dcacd20fb260e494f8',
    messagingSenderId: '503116412521',
    projectId: 'chatapp-70e51',
    authDomain: 'chatapp-70e51.firebaseapp.com',
    storageBucket: 'chatapp-70e51.appspot.com',
    measurementId: 'G-DHPRPVMBL9',
  );

}